Code refactoring + shellcheck on TravisCI

diff --git a/SOURCES/rpmunbuilder b/SOURCES/rpmunbuilder
--- a/SOURCES/rpmunbuilder
+++ b/SOURCES/rpmunbuilder
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC1117,SC2034,SC2154
 
 ########################################################################################
 
 APP="RPMUnbuilder"
-VER="1.1.4"
+VER="1.1.5"
 
 ########################################################################################
 
@@ -44,18 +45,18 @@ SHORT_ARGS="h:help v:version"
 ########################################################################################
 
 main() {
-  if [[ $ver || $version ]] ; then
+  if [[ -n "$ver" || -n "$version" ]] ; then
     about
     exit 0
   fi
 
-  if [[ $# -eq 0 || $help || $usage ]] ; then
+  if [[ $# -eq 0 || -n "$help" || -n "$usage" ]] ; then
     usage
     exit 0
   fi
 
   if [[ ! $(checkDeps "rpm" "rpm2cpio" "cpio") ]] ; then
-    error "For using this utility install this packages first: rpm rpm2cpio cpio" $BROWN
+    error "For using this utility install this packages first: rpm rpm2cpio cpio"
     exit 2
   fi
 
@@ -63,20 +64,20 @@ main() {
   local path="$2"
 
   if [[ ! $(isRPMPackage "$pkg") ]] ; then
-    error "Error! [$pkg] is not an rpm package!" $RED
+    error "Error! [$pkg] is not an rpm package!"
     exit 1
   fi
 
   if [[ -n "$path" ]] ; then
     if [[ ! $(checkPerms "$path" "DWX") ]] ; then
-      error "Error! Please check permissions for directory [$path]." $RED
+      error "Error! Please check permissions for directory [$path]."
       exit 3
     fi
   else
     path=$(pwd)
 
     if [[ ! $(checkPerms "$path" "DWX") ]] ; then
-      error "Error! Please check permissions for directory [$path]." $RED
+      error "Error! Please check permissions for directory [$path]."
       exit 3
     fi
   fi
@@ -108,9 +109,9 @@ processPackage() {
 }
 
 isRPMPackage() {
-  LC_ALL=C rpm -qp --qf "%{name}\n" "$1" &> /dev/null
+  
 
-  if [[ $? -eq 0 ]] ; then
+  if LC_ALL=C rpm -qp --qf "%{name}\n" "$1" &> /dev/null ; then
     echo 1 && return 0
   else
     echo "" && return 1
@@ -174,11 +175,11 @@ showm() {
 }
 
 error() {
-  show "$@" 1>&2
+  show "$@" $RED 1>&2
 }
 
 showArgWarn() {
-  error "Error! Unknown argument $1." $RED
+  error "Error! Unknown argument $1."
   doExit 1
 }
 
@@ -219,6 +220,7 @@ while [[ -n "$1" ]] ; do
     if [[ -z "$argn" ]] ; then
       argn=$arg
     else
+      # shellcheck disable=SC2015
       [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
       argn=$arg
     fi
@@ -248,7 +250,8 @@ while [[ -n "$1" ]] ; do
         shift && continue
       fi
 
-      [[ -n "${!argm}" && $MERGEABLE_ARGS\  =~ $argm\  ]] && declare "$argm=${!argm} ${arg[@]:1:99}" || declare "$argm=${arg[@]:1:99}"
+      # shellcheck disable=SC2015
+      [[ -n "${!argm}" && $MERGEABLE_ARGS\  =~ $argm\  ]] && declare "$argm=${!argm} ${arg[*]:1:99}" || declare "$argm=${arg[*]:1:99}"
 
       unset argm && shift && continue
     else
@@ -257,6 +260,7 @@ while [[ -n "$1" ]] ; do
       if [[ -z "$argn" ]] ; then
         argn=$arg
       else
+        # shellcheck disable=SC2015
         [[ -z "$argk" ]] && ( declare -F showArgValWarn &>/dev/null && showArgValWarn "--$argn" ) || declare "$argn=true"
         argn=$arg
       fi
@@ -276,6 +280,7 @@ while [[ -n "$1" ]] ; do
     fi
   else
     if [[ -n "$argn" ]] ; then
+      # shellcheck disable=SC2015
       [[ -n "${!argn}" && $MERGEABLE_ARGS\  =~ $argn\  ]] && declare "$argn=${!argn} $1" || declare "$argn=$1"
 
       unset argn && shift && continue
@@ -290,6 +295,7 @@ done
 
 unset arg argn argm argk
 
+# shellcheck disable=SC2015,SC2086
 [[ -n "$KEEP_ARGS" ]] && main $argv || main ${argt:1:9999}
 
 ########################################################################################
