Add improved workflow for pushing Docker images

diff --git a/.github/workflows/docker-push.yml b/.github/workflows/docker-push.yml
--- a/.github/workflows/docker-push.yml
+++ b/.github/workflows/docker-push.yml
@@ -48,7 +48,7 @@ jobs:
             exit 1
           fi
 
-          docker_file="Dockerfile"
+          docker_file="centos7.docker"
           base_image=$(grep 'FROM ' $docker_file | tail -1 | cut -f2 -d' ')
 
           if [[ -z "$base_image" ]] ; then
@@ -74,8 +74,8 @@ jobs:
 
           echo -e "::group::\033[34mDownloading built image…\033[0m"
 
-          if ! docker pull ghcr.io/${{env.IMAGE_NAME}}:latest ; then
-            echo "::error::Can't download image ghcr.io/${{env.IMAGE_NAME}}:latest"
+          if ! docker pull ghcr.io/${{env.IMAGE_NAME}}:centos7 ; then
+            echo "::error::Can't download image ghcr.io/${{env.IMAGE_NAME}}:centos7"
             exit 1
           fi
 
@@ -96,7 +96,7 @@ jobs:
             exit 1
           fi
 
-          if ! docker inspect "ghcr.io/${{env.IMAGE_NAME}}:latest" | jq -r '.[0].RootFS.Layers' | grep -q "$base_layer" ; then
+          if ! docker inspect "ghcr.io/${{env.IMAGE_NAME}}:centos7" | jq -r '.[0].RootFS.Layers' | grep -q "$base_layer" ; then
             echo "::warning::Rebuild image (reason: base image rebuilt)"
             echo "::set-output name=build::true"
             exit 0
@@ -110,13 +110,13 @@ jobs:
           context: .
           file: ${{steps.metadata.outputs.dockerfile}}
           tags: |
-            ghcr.io/${{env.IMAGE_NAME}}:latest
-            ghcr.io/${{env.IMAGE_NAME}}:${{steps.metadata.outputs.version}}
-            ${{env.IMAGE_NAME}}:latest
-            ${{env.IMAGE_NAME}}:${{steps.metadata.outputs.version}}
+            ghcr.io/${{env.IMAGE_NAME}}:centos7
+            ghcr.io/${{env.IMAGE_NAME}}:centos7-${{steps.metadata.outputs.version}}
+            ${{env.IMAGE_NAME}}:centos7
+            ${{env.IMAGE_NAME}}:centos7-${{steps.metadata.outputs.version}}
 
       - name: Show info about built Docker image
         uses: essentialkaos/docker-info-action@v1
         with:
-          image: ${{env.IMAGE_NAME}}:latest
+          image: ${{env.IMAGE_NAME}}:centos7
           show-labels: true
